[CHAI]
name = "CHAI"
description = "CHAI is a heterdyne reciever"
type = "heterodyne"
telescope = "FYST"

[CHAI.module.LFA]
name = "LFA"
pixels = 64

[CHAI.module.HFA]
name = "HFA"
pixels = 64


[Prime-Cam]
name = "Prime-Cam"
description = "Prime-Cam is a camera"
telescope = "FYST"
type = "bolometer"

[Prime-Cam.module.EoRSpec]
name = "EoRSpec"

[Prime-Cam.module.220GHz]
name = "220GHz"

[Prime-Cam.module.280GHz]
name = "280GHz"

[Prime-Cam.module.350GHz]
name = "350GHz"

[Prime-Cam.module.410GHz]
name = "410GHz"

[Prime-Cam.module.850GHz]
name = "850GHz"
